from __future__ import annotations

import os
import re
from dataclasses import dataclass


SYSTEM_PROMPT = """You are a careful text-to-SQL assistant.
Generate one SQLite SELECT query only.
Use only the provided schema.
Do not explain the query.
Do not generate INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, PRAGMA, or multiple statements."""


@dataclass(frozen=True)
class GenerationResult:
    sql: str
    provider: str
    notes: str


def build_prompt(question: str, schema_text: str) -> str:
    return f"""Schema:
{schema_text}

Question:
{question}

Return only one SQLite SELECT query."""


def generate_sql(
    question: str,
    schema_text: str,
    provider: str = "Demo rules",
    model: str = "",
    ollama_url: str = "http://localhost:11434/api/generate",
) -> GenerationResult:
    provider = provider.strip()
    if provider == "OpenAI":
        return _generate_with_openai(question, schema_text, model or "gpt-4o-mini")
    if provider == "Ollama":
        return _generate_with_ollama(
            question,
            schema_text,
            model or "llama3.1",
            ollama_url,
        )
    return _generate_with_rules(question)


def _generate_with_openai(question: str, schema_text: str, model: str) -> GenerationResult:
    if not os.getenv("OPENAI_API_KEY"):
        return GenerationResult(
            sql="",
            provider="OpenAI",
            notes="OPENAI_API_KEY is not set. Add it to your environment or use Demo rules.",
        )

    from openai import OpenAI

    client = OpenAI()
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": build_prompt(question, schema_text)},
        ],
        temperature=0,
    )
    content = response.choices[0].message.content or ""
    return GenerationResult(
        sql=_extract_sql(content),
        provider=f"OpenAI ({model})",
        notes="Generated by OpenAI from the provided schema.",
    )


def _generate_with_ollama(
    question: str,
    schema_text: str,
    model: str,
    ollama_url: str,
) -> GenerationResult:
    import requests

    prompt = f"{SYSTEM_PROMPT}\n\n{build_prompt(question, schema_text)}"
    try:
        response = requests.post(
            ollama_url,
            json={"model": model, "prompt": prompt, "stream": False},
            timeout=45,
        )
        response.raise_for_status()
    except requests.RequestException as exc:
        return GenerationResult(
            sql="",
            provider="Ollama",
            notes=f"Ollama request failed: {exc}",
        )

    content = response.json().get("response", "")
    return GenerationResult(
        sql=_extract_sql(content),
        provider=f"Ollama ({model})",
        notes="Generated by local Ollama from the provided schema.",
    )


def _generate_with_rules(question: str) -> GenerationResult:
    normalized = question.lower().strip()

    if _mentions(normalized, "drop", "delete", "update", "insert", "remove table"):
        sql = "DROP TABLE customers;"
        notes = "Demo rules intentionally generated an unsafe query so the safety layer can block it."
    elif _mentions(normalized, "month", "monthly") and _mentions(normalized, "sales", "revenue", "total"):
        sql = """
        SELECT
            strftime('%Y-%m', order_date) AS month,
            ROUND(SUM(quantity * unit_price), 2) AS total_sales
        FROM orders
        GROUP BY month
        ORDER BY month;
        """
        notes = "Matched a monthly sales pattern."
    elif _mentions(normalized, "top", "best") and _mentions(normalized, "product", "products"):
        sql = """
        SELECT
            p.product_name,
            ROUND(SUM(o.quantity * o.unit_price), 2) AS total_sales
        FROM orders AS o
        JOIN products AS p ON p.product_id = o.product_id
        GROUP BY p.product_name
        ORDER BY total_sales DESC
        LIMIT 5;
        """
        notes = "Matched a top products pattern."
    elif _mentions(normalized, "customer", "customers") and _mentions(normalized, "sales", "spend", "spent", "revenue"):
        sql = """
        SELECT
            c.customer_name,
            c.city,
            ROUND(SUM(o.quantity * o.unit_price), 2) AS total_spent
        FROM orders AS o
        JOIN customers AS c ON c.customer_id = o.customer_id
        GROUP BY c.customer_id, c.customer_name, c.city
        ORDER BY total_spent DESC;
        """
        notes = "Matched a customer spend pattern."
    elif _mentions(normalized, "category", "categories"):
        sql = """
        SELECT
            p.category,
            ROUND(SUM(o.quantity * o.unit_price), 2) AS total_sales
        FROM orders AS o
        JOIN products AS p ON p.product_id = o.product_id
        GROUP BY p.category
        ORDER BY total_sales DESC;
        """
        notes = "Matched a category sales pattern."
    elif _mentions(normalized, "orders", "order") and _mentions(normalized, "recent", "latest", "last"):
        sql = """
        SELECT
            o.order_id,
            o.order_date,
            c.customer_name,
            p.product_name,
            o.quantity,
            ROUND(o.quantity * o.unit_price, 2) AS order_total
        FROM orders AS o
        JOIN customers AS c ON c.customer_id = o.customer_id
        JOIN products AS p ON p.product_id = o.product_id
        ORDER BY o.order_date DESC
        LIMIT 10;
        """
        notes = "Matched a recent orders pattern."
    else:
        sql = """
        SELECT
            o.order_id,
            o.order_date,
            c.customer_name,
            p.product_name,
            o.quantity,
            ROUND(o.quantity * o.unit_price, 2) AS order_total
        FROM orders AS o
        JOIN customers AS c ON c.customer_id = o.customer_id
        JOIN products AS p ON p.product_id = o.product_id
        ORDER BY o.order_date;
        """
        notes = "Used a general sales order query because no specific demo pattern matched."

    return GenerationResult(
        sql=_extract_sql(sql),
        provider="Demo rules",
        notes=notes,
    )


def _mentions(text: str, *keywords: str) -> bool:
    return any(keyword in text for keyword in keywords)


def _extract_sql(text: str) -> str:
    cleaned = text.strip()
    fenced = re.search(r"```(?:sql)?\s*(.*?)```", cleaned, flags=re.IGNORECASE | re.DOTALL)
    if fenced:
        cleaned = fenced.group(1).strip()
    return cleaned
